name: Run test case

on: [push, pull_request]

jobs:

    run_test_case:

        runs-on: ubuntu-latest
      
        container:
            image: erlang:22.1
      
        steps:
        - uses: actions/checkout@v1
        - name: Run tests
          run: |
            make eunit
            make ct
            make cover
        - uses: actions/upload-artifact@v1
          if: always()
          with:
            name: logs
            path: _build/test/logs
        - uses: actions/upload-artifact@v1
          with:
            name: cover
            path: _build/test/cover

        - name: Coveralls Parallel
          uses: coverallsapp/github-action@master
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            parallel: true
            path-to-lcov: _build/test/cover/ct.coverdata # optional (default value)

        - name: Coveralls Finished
          uses: coverallsapp/github-action@master
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            parallel-finished: true

